plugins {
    kotlin("jvm") version "2.4.0"
}

description = "Kotlin source metrics backed by PMD's official Kotlin grammar and CPD engine"

kotlin {
    jvmToolchain(21) // compile on a GraalVM/JDK 21 toolchain
    compilerOptions {
        // Keep the project's Java 11 baseline.
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    }
}

dependencies {
    "api"(project(":mfcqi-core"))
    // PMD supplies its official Kotlin grammar AST and battle-tested CPD engine.
    "implementation"("net.sourceforge.pmd:pmd-kotlin:7.24.0")
}

// SpotBugs analyzes Java bytecode and is noisy/inaccurate on Kotlin-generated bytecode; skip it.
tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach { enabled = false }

// Format Kotlin with ktfmt (google style) alongside the root's google-java-format for Java.
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        target("src/**/*.kt")
        ktfmt().googleStyle()
    }
}
