import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    kotlin("jvm") version "2.4.0"
    id("com.gradleup.shadow") version "9.4.3"
    `maven-publish`
}

description = "Kotlin source metrics — ANTLR-based (kotlinx-ast), native-image friendly"

kotlin {
    jvmToolchain(21) // compile on a GraalVM/JDK 21 toolchain
    compilerOptions {
        // Keep the project's Java 11 baseline.
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    }
}

dependencies {
    "implementation"(project(":mfcqi-core"))
    // ANTLR-based Kotlin parser (no Kotlin compiler) — proven native-image friendly.
    "implementation"("com.github.kotlinx.ast:grammar-kotlin-parser-antlr-kotlin-jvm:0.1.0")
}

// SpotBugs analyzes Java bytecode and is noisy/inaccurate on Kotlin-generated bytecode; skip it.
tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach { enabled = false }

// Format Kotlin with ktfmt (google style) alongside the root's google-java-format for Java.
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        target("src/**/*.kt")
        ktfmt().googleStyle()
    }
}

// --- Maven Central publishing via a shaded jar -------------------------------------------------
// kotlinx-ast and its ANTLR-Kotlin runtime are only on JitPack (group `com.github.*`), so a normal
// POM dependency on them would be unresolvable for consumers using only Maven Central. We bundle
// just those `com.github.*` jars into the published artifact (the precedent: Dropbox/hypershard) and
// publish a POM that lists only the Central-resolvable dependencies. Everything kotlinx-ast pulls
// transitively (kotlin-reflect, com.benasher44:uuid, slf4j, kotlin-stdlib) IS on Central, so only
// the 5 JitPack jars need shading.
tasks.named<ShadowJar>("shadowJar") {
    archiveClassifier.set("all") // keep a distinct file name from the plain jar; published as ""
    dependencies {
        include(dependency("com.github.kotlinx.ast:.*:.*"))
        include(dependency("com.github.drieks.antlr-kotlin:.*:.*"))
    }
}

// Gradle Module Metadata would advertise the real (JitPack) dependencies and override the POM for
// Gradle consumers, defeating the shading. Publish POM-only.
tasks.withType<GenerateModuleMetadata>().configureEach { enabled = false }

publishing {
    publications {
        create<MavenPublication>("maven") {
            artifactId = "mfcqi-kotlin"
            // The shaded jar becomes the main artifact (republished without the "all" classifier).
            artifact(tasks.named("shadowJar")) { classifier = "" }
            artifact(tasks.named("sourcesJar"))
            artifact(tasks.named("javadocJar"))
            pom {
                name.set("mfcqi-kotlin")
                description.set(provider { project.description })
                url.set("https://github.com/integrallis/mfcqi-java")
                licenses {
                    license {
                        name.set("MIT License")
                        url.set("https://opensource.org/licenses/MIT")
                        distribution.set("repo")
                    }
                }
                developers {
                    developer {
                        id.set("bsbodden")
                        name.set("Brian Sam-Bodden")
                        email.set("bsbodden@gmail.com")
                        organization.set("Integrallis Software")
                        organizationUrl.set("https://integrallis.com")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/integrallis/mfcqi-java.git")
                    developerConnection.set("scm:git:ssh://git@github.com/integrallis/mfcqi-java.git")
                    url.set("https://github.com/integrallis/mfcqi-java")
                }
                // Dependencies the shaded jar does NOT bundle — all resolvable from Maven Central.
                withXml {
                    val deps = asNode().appendNode("dependencies")
                    fun dep(group: String, artifact: String, version: String, scope: String) {
                        deps.appendNode("dependency").apply {
                            appendNode("groupId", group)
                            appendNode("artifactId", artifact)
                            appendNode("version", version)
                            appendNode("scope", scope)
                        }
                    }
                    dep("com.integrallis", "mfcqi-core", project.version.toString(), "compile")
                    dep("org.jetbrains.kotlin", "kotlin-stdlib", "2.4.0", "compile")
                    dep("org.jetbrains.kotlin", "kotlin-reflect", "2.4.0", "runtime")
                    dep("com.benasher44", "uuid-jvm", "0.2.2", "runtime")
                    dep("org.slf4j", "slf4j-api", "2.0.16", "runtime")
                }
            }
        }
    }
    repositories {
        // Same local staging dir the other library modules use; JReleaser signs + uploads from here.
        maven {
            name = "staging"
            url = uri(rootProject.layout.buildDirectory.dir("staging-deploy").get().asFile)
        }
    }
}
