plugins {
    kotlin("jvm") version "2.4.0"
}

description = "Kotlin source metrics — ANTLR-based (kotlinx-ast), native-image friendly"

kotlin {
    jvmToolchain(21) // compile on a GraalVM/JDK 21 toolchain
    compilerOptions {
        // Keep the project's Java 11 baseline.
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    }
}

dependencies {
    "implementation"(project(":mfcqi-core"))
    // ANTLR-based Kotlin parser (no Kotlin compiler) — proven native-image friendly.
    "implementation"("com.github.kotlinx.ast:grammar-kotlin-parser-antlr-kotlin-jvm:0.1.0")
}

// SpotBugs analyzes Java bytecode and is noisy/inaccurate on Kotlin-generated bytecode; skip it.
tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach { enabled = false }

// Format Kotlin with ktfmt (google style) alongside the root's google-java-format for Java.
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        target("src/**/*.kt")
        ktfmt().googleStyle()
    }
}
