plugins {
    application
    // GraalVM native-image build (produces a self-contained `mfcqi` binary, no JRE required).
    id("org.graalvm.buildtools.native") version "0.10.4"
}

description = "Picocli-based CLI: analyze, badge, config, models subcommands"

// Native-image build. Reflection/resource config lives under
// src/main/resources/META-INF/native-image/ (Picocli's is generated by picocli-codegen).
graalvmNative {
    binaries {
        named("main") {
            imageName.set("mfcqi")
            mainClass.set("com.integrallis.mfcqi.cli.Main")
            sharedLibrary.set(false) // build a standalone executable, not a .so
            buildArgs.add("--no-fallback")
            // HttpClient (LLM + OSV.dev) needs the URL protocols and TLS baked in.
            buildArgs.add("--enable-url-protocols=http,https")
            buildArgs.add("-H:+UnlockExperimentalVMOptions")
            // Initialize SLF4J's NOP binding at build time to avoid a runtime warning/init issue.
            buildArgs.add("--initialize-at-build-time=org.slf4j")
        }
    }
    // Don't require GraalVM for the normal build/test; only nativeCompile needs it.
    toolchainDetection.set(false)
}

// The CLI is not published to Maven Central (see root build.gradle.kts). It is shipped
// as a runnable distribution (zip/tar with a bin/mfcqi launcher) attached to the GitHub
// Release. `installDist` produces a local install under build/install/mfcqi/.
application {
    applicationName = "mfcqi"
    mainClass.set("com.integrallis.mfcqi.cli.Main")
}

distributions {
    main {
        // Archive base name -> mfcqi-<version>.zip / .tar (not mfcqi-cli-<version>).
        distributionBaseName.set("mfcqi")
    }
}

dependencies {
    "implementation"(project(":mfcqi-core"))
    "implementation"(project(":mfcqi-engine"))
    "implementation"(project(":mfcqi-metrics"))
    "implementation"(project(":mfcqi-kotlin"))
    "implementation"(project(":mfcqi-duplication"))
    "implementation"(project(":mfcqi-secrets"))
    "implementation"(project(":mfcqi-smells"))
    "implementation"(project(":mfcqi-security"))
    "implementation"(project(":mfcqi-deps-security"))
    "implementation"(project(":mfcqi-analysis"))
    "api"(project(":mfcqi-quality-gates"))
    "implementation"(project(":mfcqi-badge"))
    // Picocli — Apache 2.0, no API key.
    "implementation"("info.picocli:picocli:4.7.6")
    // Generates GraalVM reflection/resource config for the Picocli commands at compile time.
    "annotationProcessor"("info.picocli:picocli-codegen:4.7.6")
    // Jackson for JSON / SARIF rendering.
    "implementation"("com.fasterxml.jackson.core:jackson-databind:2.18.2")
    // JavaParser — ToolOutputCollector walks ASTs to find complexity hotspots for the LLM prompt.
    "implementation"("com.github.javaparser:javaparser-core:3.26.4")
}
